- name: Install and configure Kafka
  hosts: kafka
  become: true
  tasks:
    - name: Install Java
      apt: name=openjdk-11-jre-headless state=present update_cache=true

    - name: Download Kafka
      get_url:
        url: https://downloads.apache.org/kafka/3.6.0/kafka_2.13-3.6.0.tgz
        dest: /opt/kafka.tgz

    - name: Extract Kafka
      unarchive:
        src: /opt/kafka.tgz
        dest: /opt/
        remote_src: yes

    - name: Start Zookeeper
      shell: "nohup /opt/kafka_2.13-3.6.0/bin/zookeeper-server-start.sh -daemon /opt/kafka_2.13-3.6.0/config/zookeeper.properties"

    - name: Start Kafka
      shell: "nohup /opt/kafka_2.13-3.6.0/bin/kafka-server-start.sh -daemon /opt/kafka_2.13-3.6.0/config/server.properties"
